### PR TITLE
Banner

### PR DESCRIPTION
**Pull request by AmirShayegh**
- Updated banner to support 2 line messages: title and detail
- POST Shift and POST Inspection functions display banner with api error message

### CODE REVIEW

**Comment by micheal-w-wells** [comment]
@jleach can you help us figure out what's up with the azure pipeline here? The first PR check is a timeout on cocoapods that is repeatable on retry, the other looks like it's puking on yaml, I'm not sure which is a test flight task vs build submission either (assuming that is what the two steps do).

**Comment by AmirShayegh** [comment]
@jleach , I think it might be the target - When I pulled from the repo, there was no target, so I added one named 'inspect'.
Could you confirm that that's the issue? I think targets may be gitignored

**Comment by AmirShayegh** [comment]
Nvm, it was just the pipeline timing out

**Comment by rstens** [comment]
> Nvm, it was just the pipeline timing out

OK, can we close this PR then?

**Pull request merged**
